package tddtry.even;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class EvenCheckerTest {
    @Test public void testIsEven() {
        
        assertTrue(new EvenChecker().isEven(2));
    }
}
